In [1]:
import torch

x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])

In [2]:
print(x.shape)

torch.Size([1, 2])


In [3]:
print(y.shape)

torch.Size([2, 1])


In [4]:
print(x.dtype)

torch.int64


The data type of all elements within a tensor is the same. That means if a
tensor contains data of different data types (such as a Boolean, an integer,
and a float), the entire tensor is coerced to the most generic data type

In [5]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


In [9]:
# Generate zeros of shape (3, 4)
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# Generate ones of shape (3, 4)
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Generate numbers between 0 and 10 that includes 0 but not 10
torch.randint(low = 0, high = 10, size = (3, 4))

tensor([[6, 3, 3, 4],
        [9, 9, 3, 2],
        [8, 5, 7, 4]])

In [14]:
torch.rand(3, 4)

tensor([[0.5343, 0.4132, 0.4919, 0.9831],
        [0.8616, 0.9313, 0.3441, 0.7005],
        [0.0884, 0.1332, 0.3862, 0.0974]])

In [16]:
torch.randn((3, 4))

tensor([[ 0.4332, -1.4659,  2.1640,  0.5670],
        [-0.8322,  1.5956, -0.8550,  0.6999],
        [-1.4062, -1.6270, -0.9495,  0.5216]])

In [18]:
import numpy as np

x = np.array([[10, 20, 30],[2, 3, 4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


# Operations on tensors

Similar to NumPy, you can perform various basic operations on tensor objects.

In [20]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x * 20)

tensor([[ 20,  40,  60,  80],
        [100, 120, 140, 160]])


In [22]:
y = x.add(10)
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


In [29]:
# Reshaping a tensor (we can use .view() to reshape a tensor)
y = torch.tensor([1, 2, 3, 4])
z = y.view(4, 1)
print(y.shape)
print(z.shape)

torch.Size([4])
torch.Size([4, 1])


Another way to reshape a tensor is by using the squeeze method, where
we provide the axis index that we want to remove. Note that this is
applicable only when the axis we want to remove has only one item in that
dimension

In [32]:
x = torch.randn(10, 1, 10)
z1 = torch.squeeze(x, 1)
z1

tensor([[ 0.8664, -1.4659,  1.2341, -0.1026,  0.3815,  1.0989, -0.6808, -1.3327,
         -0.5114,  1.4714],
        [ 0.8114,  1.2860, -0.0566,  1.9876, -0.8342, -0.3199, -0.4398,  0.5000,
         -0.3804, -0.5377],
        [-0.1329, -0.8578, -0.8241,  0.8639, -1.2762, -0.2360, -0.1777,  1.7824,
         -0.0050, -0.2272],
        [-1.2864,  1.5958, -0.5478, -0.9464,  0.3690,  0.8506, -1.6029,  1.8661,
          0.6854,  0.4302],
        [-0.1747,  0.5808, -2.1842, -0.6831,  1.1557,  1.4733,  0.2772,  1.2095,
         -1.1910,  0.8209],
        [ 0.3926,  0.0857, -0.3616, -1.0333,  1.7662,  0.1059,  1.5185, -1.1082,
          0.7572, -0.0606],
        [ 0.6859,  0.2137,  0.9917,  0.6336,  0.6245,  0.2907, -0.0204, -0.6763,
          1.0644, -1.8062],
        [ 1.6026,  0.3844,  0.0873, -0.7963,  1.7423, -2.3849, -0.1545, -0.7219,
         -0.4780,  0.2518],
        [-0.0173,  0.2594,  0.0439, -0.2430, -2.2729, -1.6757,  0.7657,  0.2559,
         -0.0700, -1.3786],
        [-0.8685,  

In [36]:
print(x.shape)
print(z1.shape)

torch.Size([10, 1, 10])
torch.Size([10, 10])


In [38]:
z2 = x.squeeze(1)
print(z2.shape)

torch.Size([10, 10])


The opposite of squeeze is unsqueeze, which means we add a dimension
to the matrix

In [40]:
x = torch.randn(10, 10)
print(x.shape)
z2 = x.unsqueeze(0)
print(z2.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])


In [41]:
# The same can be achieved using [None] indexing
# Adding None will auto create a fake dim
# at the specified axis

x = torch.randn(10, 10)
z1, z2, z3 = x[None], x[:, None], x[:, :, None]
print(z1.shape)
print(z2.shape)
print(z3.shape)

torch.Size([1, 10, 10])
torch.Size([10, 1, 10])
torch.Size([10, 10, 1])


In [46]:
# Matrix multiplication of two different tensors can be performed
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(torch.matmul(x, y))

tensor([30, 70])


In [48]:
# Matrix multiplication can also be performed using the @ sign
print(x @ y)

tensor([30, 70])


Similar to concatenate in NumPy, we can perform concatenation of
tensors using the cat method

In [54]:
x = torch.randn(10, 10, 10)
print(x.shape)
z = torch.cat([x, x], axis = 1)
print(z.shape)

torch.Size([10, 10, 10])
torch.Size([10, 20, 10])


In [63]:
# Extraction of the maximum value in a tensor
x = torch.arange(25).reshape(5, 5)
x.max()

tensor(24)

In [66]:
x.max(dim = 0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

` .max` returns both the maximum values and the location (argmax) of the maximum values.


In [67]:
m, arg_m = x.max(dim = 0)

In [68]:
m

tensor([20, 21, 22, 23, 24])

In [69]:
arg_m

tensor([4, 4, 4, 4, 4])

In [76]:
# Permute the dimensions of a tensor object (just to change the shape dimension of the tensor) 
# -> first one to second and like that
# Note that the shape of the tensor changes when we perform permute on top of the original tensor.

x = torch.randn(10, 20, 30)
z = x.permute(2, 0, 1)
print(x.shape)
print(z.shape)

torch.Size([10, 20, 30])
torch.Size([30, 10, 20])


 PyTorch with almost the same
syntax as NumPy. Standard mathematical operations, such as abs, add, argsort,
ceil, floor, sin, cos, tan, cumsum, cumprod, diag, eig, exp, log, log2, log10,
mean, median, mode, resize, round, sigmoid, softmax, square, sqrt, svd,
and transpose. You can always run `dir(torch.Tensor)` to see all the
methods possible for a Torch tensor

In [79]:
list(dir(torch.Tensor))

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__cuda_array_interface__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__