In [1]:
import torch

# Tensors

PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional
array

In [2]:
# Lets create a tensor with single number
t1 = torch.tensor(4.) # 4.  means 4.0, it is a process of creating floating point numbers
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

Let's try creating a slightly more complex tensors

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Lets create a matrix of 3 rows and two columns
t3 = torch.tensor([[5., 6],
                  [7., 8],
                  [9., 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# A 3-dimensional arrays
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15,  16, 17],
     [17, 18, 19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the
length along each dimension using the .shape property of a tensor.

In [9]:
# t1 is a scalar with no dimensions
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [10]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [12]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [14]:
# To check for the 3 dimension
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

# Tensor operations and gradients
We can combine tensors with usual arithmetic operations 

In [18]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [19]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

What makes PyTorch special is that we can
automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and
b. To compute the derivatives, we can call the .backward method on our result y .


In [20]:
# Compute the derivatives
y.backward()

In [21]:
# Display gradients
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


dy/dw has the same value as x i.e. 3 , and dy/db has the value 1 . Note that x.grad is
None , because x doesn't have requires_grad set to True .
The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with
matrices.

# Interoperability with Numpy

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem
of tools and libraries.

In [23]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy .`

In [24]:
# Converting the numpy array to a tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify

In [25]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor

In [26]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will
likely be read and preprocessed as Numpy arrays.
